package com.bancomat.springmvc.entity;
// Generated 7-nov-2016 12.41.09 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Movimenti generated by hbm2java
 */
public class Movimenti  implements java.io.Serializable {


     private int idMovimento;
     private Date data;
     private int idUtente;
     private String causale;
     private double importo;

    public Movimenti() {
    }

    public Movimenti(int idMovimento, Date data, int idUtente, String causale, double importo) {
       this.idMovimento = idMovimento;
       this.data = data;
       this.idUtente = idUtente;
       this.causale = causale;
       this.importo = importo;
    }
   
    public int getIdMovimento() {
        return this.idMovimento;
    }
    
    public void setIdMovimento(int idMovimento) {
        this.idMovimento = idMovimento;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getIdUtente() {
        return this.idUtente;
    }
    
    public void setIdUtente(int idUtente) {
        this.idUtente = idUtente;
    }
    public String getCausale() {
        return this.causale;
    }
    
    public void setCausale(String causale) {
        this.causale = causale;
    }
    public double getImporto() {
        return this.importo;
    }
    
    public void setImporto(double importo) {
        this.importo = importo;
    }

}


